services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
    ports:
      - "9000:9000"

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    depends_on:
      - app

  database:
   image: postgres:11.2
   volumes:
     - dbdata:/var/lib/pgsql
   environment:
     - "POSTGRES_DB=mydb"
     - "POSTGRES_USER=myuser"
     - "POSTGRES_PASSWORD=expensecontrolpassword"
   ports:
       - "54321:5432"

  selenium:
    image: selenium/standalone-chrome

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  node:
    image: node:18.19.1
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["/var/www/entrypoint.sh"]
    ports:  
      -  "5173:5173"

volumes:
  dbdata: {}