services:
  app:
    container_name: laravel-app
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
    ports:
      - "3101:80"
    depends_on:
      - database
    networks:
      - app-network

  database:
    container_name: laravel-database
    image: postgres:11.2
    volumes:
      - dbdata:/var/lib/pgsql
    environment:
      - "POSTGRES_DB=mydb"
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=expensecontrolpassword"
    ports:
      - "54321:5432"
    networks:
      - app-network

volumes:
  dbdata: {}

networks:
  app-network:
    driver: bridge
